Add form validation to add user
UMM-CSci-3601/3601-lab4_mongo pull request #79
Opened 2019-02-01 01:58 UTC by kklamberty

This commit addresses #28 and includes several end-to-end tests of the form validation. There are a few tests missing (user name being too short or too long), but give a good idea about how this works. We should probably add those, but this is real progress toward this issue and could maybe close it.

2019-02-01 02:04 UTC, kklamberty commented
E2E seem to pass for me as well as the tests run for a successful build, by the way.

2019-02-04 20:08 UTC, NicMcPhee requested changes
This all looks really cool, and I'm actually happy if you just merge it as is. There are a couple of small refactorings, though, that would both help improve the readability of the code and demonstrate how they can/should clean up duplication in their code is well.

Thanks!

2019-02-04 20:08 UTC, NicMcPhee commented on client/src/app/users/name.validator.ts
> +export class NameValidator {
Nice to have included an example of a custom validator. Your comments, though, imply that it's not "working as it should"? Does it not actually work? Are there issues we should try to address?

2019-02-05 21:05 UTC, kklamberty commented on client/e2e/user-list.e2e-spec.ts
> +// This line (combined with the function that follows) is here for us
Yes

2019-02-05 21:08 UTC, kklamberty commented on client/e2e/user-list.e2e-spec.ts
> +        // Need to use backspace because the default value is -1. If that changes, this will change too.
Maybe we can clear the field from our e2e test and still avoid putting the test functionality itself into the page objects.

2019-02-05 21:09 UTC, kklamberty commented on client/e2e/user-list.e2e-spec.ts
> +        expect(page.field('nameField').isPresent()).toBeTruthy('There should be a name field');
Yes - let's put that function in the e2e test (not in page objects)

2019-02-05 23:08 UTC, kklamberty commented on client/e2e/user-list.e2e-spec.ts
> +        expect(page.field('nameField').isPresent()).toBeTruthy('There should be a name field');
For now, let's not change this. Thinking more about this, a failure is easier to detect when we know from which test it failed.

2019-02-05 23:09 UTC, kklamberty commented on client/src/app/custom.module.ts
> +
```suggestion
```

2019-02-06 02:11 UTC, NicMcPhee approved these changes
@kklamberty and I spent several hours on some refactoring and improvements that address my various comments here. I think we're good to commit!

2019-02-06 03:46 UTC, merged

2019-02-20 18:19 UTC, kklamberty commented
Closes #28